# -*- coding: utf-8 -*-
"""Wine_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZqcKBbqMbR80mdWjHBtX5vTLJAiyYcZ3
"""

from __future__ import print_function
import argparse
import os
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument('--output-data-dir', type=str, default=os.getenv('SM_OUTPUT_DATA_DIR', '/opt/ml/output/data'))
  parser.add_argument('--model-dir', type=str, default=os.getenv('SM_MODEL_DIR', '/opt/ml/model'))
  parser.add_argument('--train', type=str, default=os.getenv('SM_CHANNEL_TRAIN', '/opt/ml/input/data/train'))
  args = parser.parse_args()
  file = os.path.join(args.train, 'wine_quality.csv')
  dataset = pd.read_csv(file, engine = 'python')
  X = dataset.iloc[:, :11]
  y = dataset.iloc[:, 11]
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)
  linear_model = LinearRegression()
  linear_model.fit(X_train, y_train)
  model_path = os.path.join(args.model_dir, 'model.pkl')
    with open(model_path, 'wb') as model_file:
        pickle.dump(linear_model, model_file)


def model_fn(model_dir):
  linear_model = pickle.load(open(os.path.join(model_dir, 'model.pkl'), 'rb'))
  return linear_model